/* Automatically @generated by tree-sitter */

#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 14
#define STATE_COUNT 33
#define LARGE_STATE_COUNT 4
#define SYMBOL_COUNT 20
#define ALIAS_COUNT 0
#define TOKEN_COUNT 11
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 7
#define MAX_ALIAS_SEQUENCE_LENGTH 3
#define MAX_RESERVED_WORD_SET_SIZE 0
#define PRODUCTION_ID_COUNT 6
#define SUPERTYPE_COUNT 0

enum ts_symbol_identifiers {
  sym__newline = 1,
  sym_comment = 2,
  anon_sym_type = 3,
  anon_sym_stmt = 4,
  anon_sym_COLON = 5,
  aux_sym_identifier_token1 = 6,
  anon_sym_DQUOTE = 7,
  sym_string_content = 8,
  anon_sym_AT = 9,
  sym_escape_sequence = 10,
  sym_source_file = 11,
  sym_type_declaration = 12,
  sym_statement = 13,
  sym_stmt_keyword = 14,
  sym_identifier = 15,
  sym_string = 16,
  sym_reference = 17,
  aux_sym_source_file_repeat1 = 18,
  aux_sym_string_repeat1 = 19,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [sym__newline] = "_newline",
  [sym_comment] = "comment",
  [anon_sym_type] = "type",
  [anon_sym_stmt] = "stmt",
  [anon_sym_COLON] = ":",
  [aux_sym_identifier_token1] = "identifier_token1",
  [anon_sym_DQUOTE] = "\"",
  [sym_string_content] = "string_content",
  [anon_sym_AT] = "@",
  [sym_escape_sequence] = "escape_sequence",
  [sym_source_file] = "source_file",
  [sym_type_declaration] = "type_declaration",
  [sym_statement] = "statement",
  [sym_stmt_keyword] = "stmt_keyword",
  [sym_identifier] = "identifier",
  [sym_string] = "string",
  [sym_reference] = "reference",
  [aux_sym_source_file_repeat1] = "source_file_repeat1",
  [aux_sym_string_repeat1] = "string_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [sym__newline] = sym__newline,
  [sym_comment] = sym_comment,
  [anon_sym_type] = anon_sym_type,
  [anon_sym_stmt] = anon_sym_stmt,
  [anon_sym_COLON] = anon_sym_COLON,
  [aux_sym_identifier_token1] = aux_sym_identifier_token1,
  [anon_sym_DQUOTE] = anon_sym_DQUOTE,
  [sym_string_content] = sym_string_content,
  [anon_sym_AT] = anon_sym_AT,
  [sym_escape_sequence] = sym_escape_sequence,
  [sym_source_file] = sym_source_file,
  [sym_type_declaration] = sym_type_declaration,
  [sym_statement] = sym_statement,
  [sym_stmt_keyword] = sym_stmt_keyword,
  [sym_identifier] = sym_identifier,
  [sym_string] = sym_string,
  [sym_reference] = sym_reference,
  [aux_sym_source_file_repeat1] = aux_sym_source_file_repeat1,
  [aux_sym_string_repeat1] = aux_sym_string_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [sym__newline] = {
    .visible = false,
    .named = true,
  },
  [sym_comment] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_type] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_stmt] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COLON] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_identifier_token1] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_DQUOTE] = {
    .visible = true,
    .named = false,
  },
  [sym_string_content] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_AT] = {
    .visible = true,
    .named = false,
  },
  [sym_escape_sequence] = {
    .visible = true,
    .named = true,
  },
  [sym_source_file] = {
    .visible = true,
    .named = true,
  },
  [sym_type_declaration] = {
    .visible = true,
    .named = true,
  },
  [sym_statement] = {
    .visible = true,
    .named = true,
  },
  [sym_stmt_keyword] = {
    .visible = true,
    .named = true,
  },
  [sym_identifier] = {
    .visible = true,
    .named = true,
  },
  [sym_string] = {
    .visible = true,
    .named = true,
  },
  [sym_reference] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_source_file_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_string_repeat1] = {
    .visible = false,
    .named = false,
  },
};

enum ts_field_identifiers {
  field_description = 1,
  field_id = 2,
  field_keyword = 3,
  field_name = 4,
  field_stmt_kw = 5,
  field_type = 6,
  field_value = 7,
};

static const char * const ts_field_names[] = {
  [0] = NULL,
  [field_description] = "description",
  [field_id] = "id",
  [field_keyword] = "keyword",
  [field_name] = "name",
  [field_stmt_kw] = "stmt_kw",
  [field_type] = "type",
  [field_value] = "value",
};

static const TSMapSlice ts_field_map_slices[PRODUCTION_ID_COUNT] = {
  [1] = {.index = 0, .length = 3},
  [2] = {.index = 3, .length = 1},
  [3] = {.index = 4, .length = 1},
  [4] = {.index = 5, .length = 3},
  [5] = {.index = 8, .length = 3},
};

static const TSFieldMapEntry ts_field_map_entries[] = {
  [0] =
    {field_description, 2},
    {field_keyword, 0},
    {field_name, 1},
  [3] =
    {field_type, 2},
  [4] =
    {field_id, 1},
  [5] =
    {field_id, 1},
    {field_stmt_kw, 0},
    {field_value, 2},
  [8] =
    {field_id, 1},
    {field_stmt_kw, 2},
    {field_value, 0},
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
  [3] = {
    [1] = sym_identifier,
  },
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 9,
  [13] = 13,
  [14] = 14,
  [15] = 15,
  [16] = 7,
  [17] = 17,
  [18] = 18,
  [19] = 19,
  [20] = 20,
  [21] = 21,
  [22] = 22,
  [23] = 23,
  [24] = 24,
  [25] = 4,
  [26] = 20,
  [27] = 27,
  [28] = 5,
  [29] = 15,
  [30] = 30,
  [31] = 8,
  [32] = 10,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(12);
      ADVANCE_MAP(
        '\n', 13,
        '"', 19,
        '/', 2,
        ':', 17,
        '@', 22,
        '\\', 10,
        's', 7,
        't', 9,
      );
      if (lookahead == '\t' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(11);
      END_STATE();
    case 1:
      if (lookahead == '"') ADVANCE(19);
      if (lookahead == '@') ADVANCE(22);
      if (lookahead == '\\') ADVANCE(10);
      if (lookahead == '\t' ||
          lookahead == '\r' ||
          lookahead == ' ') ADVANCE(20);
      if (lookahead != 0) ADVANCE(21);
      END_STATE();
    case 2:
      if (lookahead == '/') ADVANCE(14);
      END_STATE();
    case 3:
      if (lookahead == ':') ADVANCE(17);
      if (lookahead == '\t' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(3);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(18);
      END_STATE();
    case 4:
      if (lookahead == 'e') ADVANCE(15);
      END_STATE();
    case 5:
      if (lookahead == 'm') ADVANCE(8);
      END_STATE();
    case 6:
      if (lookahead == 'p') ADVANCE(4);
      END_STATE();
    case 7:
      if (lookahead == 't') ADVANCE(5);
      END_STATE();
    case 8:
      if (lookahead == 't') ADVANCE(16);
      END_STATE();
    case 9:
      if (lookahead == 'y') ADVANCE(6);
      END_STATE();
    case 10:
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(23);
      END_STATE();
    case 11:
      if (eof) ADVANCE(12);
      if (lookahead == '\n') ADVANCE(13);
      if (lookahead == '"') ADVANCE(19);
      if (lookahead == '/') ADVANCE(2);
      if (lookahead == ':') ADVANCE(17);
      if (lookahead == 's') ADVANCE(7);
      if (lookahead == 't') ADVANCE(9);
      if (lookahead == '\t' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(11);
      END_STATE();
    case 12:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 13:
      ACCEPT_TOKEN(sym__newline);
      END_STATE();
    case 14:
      ACCEPT_TOKEN(sym_comment);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(14);
      END_STATE();
    case 15:
      ACCEPT_TOKEN(anon_sym_type);
      END_STATE();
    case 16:
      ACCEPT_TOKEN(anon_sym_stmt);
      END_STATE();
    case 17:
      ACCEPT_TOKEN(anon_sym_COLON);
      END_STATE();
    case 18:
      ACCEPT_TOKEN(aux_sym_identifier_token1);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(18);
      END_STATE();
    case 19:
      ACCEPT_TOKEN(anon_sym_DQUOTE);
      END_STATE();
    case 20:
      ACCEPT_TOKEN(sym_string_content);
      if (lookahead == '\t' ||
          lookahead == '\r' ||
          lookahead == ' ') ADVANCE(20);
      if (lookahead != 0 &&
          lookahead != '"' &&
          lookahead != '@' &&
          lookahead != '\\') ADVANCE(21);
      END_STATE();
    case 21:
      ACCEPT_TOKEN(sym_string_content);
      if (lookahead != 0 &&
          lookahead != '"' &&
          lookahead != '@' &&
          lookahead != '\\') ADVANCE(21);
      END_STATE();
    case 22:
      ACCEPT_TOKEN(anon_sym_AT);
      END_STATE();
    case 23:
      ACCEPT_TOKEN(sym_escape_sequence);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 0},
  [2] = {.lex_state = 0},
  [3] = {.lex_state = 0},
  [4] = {.lex_state = 0},
  [5] = {.lex_state = 0},
  [6] = {.lex_state = 0},
  [7] = {.lex_state = 1},
  [8] = {.lex_state = 0},
  [9] = {.lex_state = 1},
  [10] = {.lex_state = 0},
  [11] = {.lex_state = 1},
  [12] = {.lex_state = 1},
  [13] = {.lex_state = 0},
  [14] = {.lex_state = 0},
  [15] = {.lex_state = 0},
  [16] = {.lex_state = 1},
  [17] = {.lex_state = 1},
  [18] = {.lex_state = 3},
  [19] = {.lex_state = 0},
  [20] = {.lex_state = 3},
  [21] = {.lex_state = 3},
  [22] = {.lex_state = 0},
  [23] = {.lex_state = 0},
  [24] = {.lex_state = 3},
  [25] = {.lex_state = 3},
  [26] = {.lex_state = 3},
  [27] = {.lex_state = 3},
  [28] = {.lex_state = 3},
  [29] = {.lex_state = 3},
  [30] = {.lex_state = 0},
  [31] = {.lex_state = 3},
  [32] = {.lex_state = 3},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [STATE(0)] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [sym__newline] = ACTIONS(1),
    [sym_comment] = ACTIONS(1),
    [anon_sym_type] = ACTIONS(1),
    [anon_sym_stmt] = ACTIONS(1),
    [anon_sym_COLON] = ACTIONS(1),
    [anon_sym_DQUOTE] = ACTIONS(1),
    [anon_sym_AT] = ACTIONS(1),
    [sym_escape_sequence] = ACTIONS(1),
  },
  [STATE(1)] = {
    [sym_source_file] = STATE(30),
    [sym_type_declaration] = STATE(2),
    [sym_statement] = STATE(2),
    [sym_stmt_keyword] = STATE(24),
    [sym_string] = STATE(21),
    [aux_sym_source_file_repeat1] = STATE(2),
    [ts_builtin_sym_end] = ACTIONS(3),
    [sym__newline] = ACTIONS(5),
    [sym_comment] = ACTIONS(5),
    [anon_sym_type] = ACTIONS(7),
    [anon_sym_stmt] = ACTIONS(9),
    [anon_sym_DQUOTE] = ACTIONS(11),
  },
  [STATE(2)] = {
    [sym_type_declaration] = STATE(3),
    [sym_statement] = STATE(3),
    [sym_stmt_keyword] = STATE(24),
    [sym_string] = STATE(21),
    [aux_sym_source_file_repeat1] = STATE(3),
    [ts_builtin_sym_end] = ACTIONS(13),
    [sym__newline] = ACTIONS(15),
    [sym_comment] = ACTIONS(15),
    [anon_sym_type] = ACTIONS(7),
    [anon_sym_stmt] = ACTIONS(9),
    [anon_sym_DQUOTE] = ACTIONS(11),
  },
  [STATE(3)] = {
    [sym_type_declaration] = STATE(3),
    [sym_statement] = STATE(3),
    [sym_stmt_keyword] = STATE(24),
    [sym_string] = STATE(21),
    [aux_sym_source_file_repeat1] = STATE(3),
    [ts_builtin_sym_end] = ACTIONS(17),
    [sym__newline] = ACTIONS(19),
    [sym_comment] = ACTIONS(19),
    [anon_sym_type] = ACTIONS(22),
    [anon_sym_stmt] = ACTIONS(25),
    [anon_sym_DQUOTE] = ACTIONS(28),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 2,
    ACTIONS(33), 1,
      anon_sym_COLON,
    ACTIONS(31), 6,
      ts_builtin_sym_end,
      sym__newline,
      sym_comment,
      anon_sym_type,
      anon_sym_stmt,
      anon_sym_DQUOTE,
  [12] = 1,
    ACTIONS(35), 6,
      ts_builtin_sym_end,
      sym__newline,
      sym_comment,
      anon_sym_type,
      anon_sym_stmt,
      anon_sym_DQUOTE,
  [21] = 1,
    ACTIONS(37), 6,
      ts_builtin_sym_end,
      sym__newline,
      sym_comment,
      anon_sym_type,
      anon_sym_stmt,
      anon_sym_DQUOTE,
  [30] = 4,
    ACTIONS(39), 1,
      anon_sym_DQUOTE,
    ACTIONS(43), 1,
      anon_sym_AT,
    ACTIONS(41), 2,
      sym_string_content,
      sym_escape_sequence,
    STATE(11), 2,
      sym_reference,
      aux_sym_string_repeat1,
  [45] = 1,
    ACTIONS(45), 6,
      ts_builtin_sym_end,
      sym__newline,
      sym_comment,
      anon_sym_type,
      anon_sym_stmt,
      anon_sym_DQUOTE,
  [54] = 4,
    ACTIONS(43), 1,
      anon_sym_AT,
    ACTIONS(47), 1,
      anon_sym_DQUOTE,
    ACTIONS(49), 2,
      sym_string_content,
      sym_escape_sequence,
    STATE(16), 2,
      sym_reference,
      aux_sym_string_repeat1,
  [69] = 1,
    ACTIONS(51), 6,
      ts_builtin_sym_end,
      sym__newline,
      sym_comment,
      anon_sym_type,
      anon_sym_stmt,
      anon_sym_DQUOTE,
  [78] = 4,
    ACTIONS(53), 1,
      anon_sym_DQUOTE,
    ACTIONS(58), 1,
      anon_sym_AT,
    ACTIONS(55), 2,
      sym_string_content,
      sym_escape_sequence,
    STATE(11), 2,
      sym_reference,
      aux_sym_string_repeat1,
  [93] = 4,
    ACTIONS(43), 1,
      anon_sym_AT,
    ACTIONS(61), 1,
      anon_sym_DQUOTE,
    ACTIONS(63), 2,
      sym_string_content,
      sym_escape_sequence,
    STATE(7), 2,
      sym_reference,
      aux_sym_string_repeat1,
  [108] = 1,
    ACTIONS(65), 6,
      ts_builtin_sym_end,
      sym__newline,
      sym_comment,
      anon_sym_type,
      anon_sym_stmt,
      anon_sym_DQUOTE,
  [117] = 1,
    ACTIONS(67), 6,
      ts_builtin_sym_end,
      sym__newline,
      sym_comment,
      anon_sym_type,
      anon_sym_stmt,
      anon_sym_DQUOTE,
  [126] = 1,
    ACTIONS(69), 6,
      ts_builtin_sym_end,
      sym__newline,
      sym_comment,
      anon_sym_type,
      anon_sym_stmt,
      anon_sym_DQUOTE,
  [135] = 4,
    ACTIONS(43), 1,
      anon_sym_AT,
    ACTIONS(71), 1,
      anon_sym_DQUOTE,
    ACTIONS(41), 2,
      sym_string_content,
      sym_escape_sequence,
    STATE(11), 2,
      sym_reference,
      aux_sym_string_repeat1,
  [150] = 2,
    ACTIONS(73), 1,
      anon_sym_DQUOTE,
    ACTIONS(75), 3,
      sym_string_content,
      anon_sym_AT,
      sym_escape_sequence,
  [159] = 2,
    ACTIONS(77), 1,
      aux_sym_identifier_token1,
    STATE(19), 1,
      sym_identifier,
  [166] = 2,
    ACTIONS(79), 1,
      anon_sym_DQUOTE,
    STATE(6), 1,
      sym_string,
  [173] = 2,
    ACTIONS(81), 1,
      aux_sym_identifier_token1,
    STATE(32), 1,
      sym_identifier,
  [180] = 2,
    ACTIONS(77), 1,
      aux_sym_identifier_token1,
    STATE(23), 1,
      sym_identifier,
  [187] = 2,
    ACTIONS(79), 1,
      anon_sym_DQUOTE,
    STATE(13), 1,
      sym_string,
  [194] = 2,
    ACTIONS(83), 1,
      anon_sym_stmt,
    STATE(14), 1,
      sym_stmt_keyword,
  [201] = 2,
    ACTIONS(77), 1,
      aux_sym_identifier_token1,
    STATE(22), 1,
      sym_identifier,
  [208] = 2,
    ACTIONS(31), 1,
      aux_sym_identifier_token1,
    ACTIONS(85), 1,
      anon_sym_COLON,
  [215] = 2,
    ACTIONS(77), 1,
      aux_sym_identifier_token1,
    STATE(10), 1,
      sym_identifier,
  [222] = 1,
    ACTIONS(87), 1,
      aux_sym_identifier_token1,
  [226] = 1,
    ACTIONS(35), 1,
      aux_sym_identifier_token1,
  [230] = 1,
    ACTIONS(69), 1,
      aux_sym_identifier_token1,
  [234] = 1,
    ACTIONS(89), 1,
      ts_builtin_sym_end,
  [238] = 1,
    ACTIONS(45), 1,
      aux_sym_identifier_token1,
  [242] = 1,
    ACTIONS(51), 1,
      aux_sym_identifier_token1,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(4)] = 0,
  [SMALL_STATE(5)] = 12,
  [SMALL_STATE(6)] = 21,
  [SMALL_STATE(7)] = 30,
  [SMALL_STATE(8)] = 45,
  [SMALL_STATE(9)] = 54,
  [SMALL_STATE(10)] = 69,
  [SMALL_STATE(11)] = 78,
  [SMALL_STATE(12)] = 93,
  [SMALL_STATE(13)] = 108,
  [SMALL_STATE(14)] = 117,
  [SMALL_STATE(15)] = 126,
  [SMALL_STATE(16)] = 135,
  [SMALL_STATE(17)] = 150,
  [SMALL_STATE(18)] = 159,
  [SMALL_STATE(19)] = 166,
  [SMALL_STATE(20)] = 173,
  [SMALL_STATE(21)] = 180,
  [SMALL_STATE(22)] = 187,
  [SMALL_STATE(23)] = 194,
  [SMALL_STATE(24)] = 201,
  [SMALL_STATE(25)] = 208,
  [SMALL_STATE(26)] = 215,
  [SMALL_STATE(27)] = 222,
  [SMALL_STATE(28)] = 226,
  [SMALL_STATE(29)] = 230,
  [SMALL_STATE(30)] = 234,
  [SMALL_STATE(31)] = 238,
  [SMALL_STATE(32)] = 242,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 0, 0, 0),
  [5] = {.entry = {.count = 1, .reusable = true}}, SHIFT(2),
  [7] = {.entry = {.count = 1, .reusable = true}}, SHIFT(18),
  [9] = {.entry = {.count = 1, .reusable = true}}, SHIFT(25),
  [11] = {.entry = {.count = 1, .reusable = true}}, SHIFT(12),
  [13] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 1, 0, 0),
  [15] = {.entry = {.count = 1, .reusable = true}}, SHIFT(3),
  [17] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0),
  [19] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(3),
  [22] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(18),
  [25] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(25),
  [28] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(12),
  [31] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_stmt_keyword, 1, 0, 0),
  [33] = {.entry = {.count = 1, .reusable = true}}, SHIFT(26),
  [35] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_string, 2, 0, 0),
  [37] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_type_declaration, 3, 0, 1),
  [39] = {.entry = {.count = 1, .reusable = false}}, SHIFT(29),
  [41] = {.entry = {.count = 1, .reusable = true}}, SHIFT(11),
  [43] = {.entry = {.count = 1, .reusable = true}}, SHIFT(27),
  [45] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_identifier, 1, 0, 0),
  [47] = {.entry = {.count = 1, .reusable = false}}, SHIFT(5),
  [49] = {.entry = {.count = 1, .reusable = true}}, SHIFT(16),
  [51] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_stmt_keyword, 3, 0, 2),
  [53] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_string_repeat1, 2, 0, 0),
  [55] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_string_repeat1, 2, 0, 0), SHIFT_REPEAT(11),
  [58] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_string_repeat1, 2, 0, 0), SHIFT_REPEAT(27),
  [61] = {.entry = {.count = 1, .reusable = false}}, SHIFT(28),
  [63] = {.entry = {.count = 1, .reusable = true}}, SHIFT(7),
  [65] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_statement, 3, 0, 4),
  [67] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_statement, 3, 0, 5),
  [69] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_string, 3, 0, 0),
  [71] = {.entry = {.count = 1, .reusable = false}}, SHIFT(15),
  [73] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_reference, 2, 0, 3),
  [75] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_reference, 2, 0, 3),
  [77] = {.entry = {.count = 1, .reusable = true}}, SHIFT(8),
  [79] = {.entry = {.count = 1, .reusable = true}}, SHIFT(9),
  [81] = {.entry = {.count = 1, .reusable = true}}, SHIFT(31),
  [83] = {.entry = {.count = 1, .reusable = true}}, SHIFT(4),
  [85] = {.entry = {.count = 1, .reusable = true}}, SHIFT(20),
  [87] = {.entry = {.count = 1, .reusable = true}}, SHIFT(17),
  [89] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_axm(void) {
  static const TSLanguage language = {
    .abi_version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .field_names = ts_field_names,
    .field_map_slices = ts_field_map_slices,
    .field_map_entries = ts_field_map_entries,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = (const void*)ts_lex_modes,
    .lex_fn = ts_lex,
    .primary_state_ids = ts_primary_state_ids,
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
